### ISSUE TITLE
Error overview page does not work with Npgsql 4.x (Postgre)

### ISSUE THREAD

**Issue by Mochitoto** [atifaziz/PgsqlErrorLog#3]
The guid cannot be directly converted to string.

Following error appears on requesting list of errors:
![image](https://user-images.githubusercontent.com/12380018/69052113-765b5500-0a06-11ea-8f53-235c922681e3.png)

After a short investigation in the source of PgsqlErrorLog I found following line of code to be the culprit:
![image](https://user-images.githubusercontent.com/12380018/69052851-59c01c80-0a08-11ea-8b6e-c1132b4a081e.png)

**Comment by laimis** [comment]
The PR has been merged.
